version: '3'
services:
  redis:
    container_name: redis
    hostname: redis
    image: redis
    volumes: 
    - redis_volume

  pythonredis:
    container_name: redispy
    build: ./scripts

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - "8081:8081"

volumes: 
    redis_volume: