version: '3'
services:
  redis_db_1:
    container_name: redis_db_1
    hostname: redis_db_1
    image: redis
    ports: 
    - 6379:6379

  redis_db_2:
    container_name: redis_db_2
    hostname: redis_db_2
    image: redis
    ports: 
    - 4000:6379

  redis_db_3:
    container_name: redis_db_3
    hostname: redis_db_3
    image: redis
    ports: 
    - 5000:6379

  redis-commander:
    container_name: redis_dbms
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=redis_db_1,redis_db_2,redis_db_3
    - HTTP_USER=DASistemas
    - HTTP_PASSWORD=2do-parcial!
    ports:
    - "8081:8081"