version: "3.8"
services: 
    db:
        container_name: mongo_db
        image: mongo:4.2
        restart: always
        ports: 
            - "27027:27017"
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=foo
            - MONGO_INITDB_ROOT_PASSWORD=bar123
            - MONGO_INITDB_DATABASE=baz
        volumes: 
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
