version: '3.1'
services:

  db:
    container_name: database_mysql 
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ordinario123!
      MYSQL_USER: extra
      MYSQL_PASSWORD: ordinario123!
      MYSQL_DATABASE: pruebas
    ports:
      - 4444:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080