version: '3.8'

services:

  mongo:
    container_name: mongo_db
    image: mongo:4.2
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: foo
      MONGO_INITDB_ROOT_PASSWORD: bar123
      MONGO_INITDB_DATABASE: faz

  mongo-express:
    container_name: mongo_express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: foo
      ME_CONFIG_MONGODB_ADMINPASSWORD: bar123