version: "3.3"
services:
    redis:
        container_name: redis_db_1
        ports: 
            - "5000:6379"
        image: redis
    
    redis2:
        container_name: redis_db_2
        ports: 
            - "27027:6379"
        image: redis

    redis3:
        container_name: redis_db_3
        ports: 
            - "6379:6379"
        image: redis
    
    redis-commander:
        container_name: redis_dbms
        image: rediscommander/redis-commander:latest
        environment: 
            - HTTP_USER=DASistemas
            - HTTP_PASSWORD=2do-parcial!
            - REDIS_HOSTS=redis_db_1,redis_db_2,redis_db_3
        ports: 
            - "8081:8081"
    
networks:
    default:
        external: 
            name: Ejercicio2