version: "3.8"

services:
#contenedor mysql
    mysql:
        container_name: mysql1
        image: mysql:latest
        ports: 
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=issue 
            - MYSQL_USER=user
            - MYSQL_PASSWORD=pass1234
        volumes: 
            - /docker:/var/lib/mysql
#contenedor phpmyadmin
    phpmyadmin:
        container_name: phpmyadmin1
        image: phpmyadmin/phpmyadmin
        expose: 
            - 80
        ports: 
            - 8081:80
        environment: 
            - PMA_HOST=mysql
        depends_on: 
            - mysql
#contenedor getdata (nuestra app)
    getdata:
        container_name: getdata
        build: ./app
        ports: 
            - 5000:5000
        depends_on: 
            - mysql