version: '3'
services:

  redis:
    container_name: redis
    hostname: redis
    image: redis
    volumes: 
      - redis_volume
  
  app:
    container_name: app
    build: ./app
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes: 
      - redis_volume:/usr/src/app
    depends_on:
      - redis
  
volumes: 
  redis_volume: