version: "3.7"

services:

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    container_name: 
      - redisdb1
    volumes:
      - redis-data:/data
    container_name: redis_db_1

  redis2:
    image: redis:latest
    ports:
      - 6380:6379
    volumes:
      - redis-data:/data
    container_name: redis_db_2

  redis3:
    image: redis:latest
    ports:
      - 6381:6379
    container_name: 
      - redisdb3
    volumes:
      - redis-data:/data
    container_name: redis_db_3

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis_db_1:6379,local:redis_db_2:6379,local:redis_db_3:6379
      - HTTP_USER=DASistemas
      - HTTP_PASSWORD=2do_Parcial!
    ports:
      - 8081:8081
    depends_on:
      - redis
      - redis2
      - redis3
    
volumes:
  redis-data: