version: '3.2'

services:
  redis:
    image: redis:latest
    container_name: redis1
    ports:
      - 6379:6379
    networks:
      - practica2

  redis2:
    image: redis:latest
    container_name: redis2
    ports:
      - 6380:6379
    networks:
      - practica2

  redis3:
    image: redis:latest
    container_name: redis3
    ports:
      - 6381:6379
    networks:
      - practica2

  redis-commander:
    container_name: redis_dbms
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=172.21.0.2:redis1:6379,172.21.0.3:redis2:6379,172.21.0.4:redis3:6379
      - HTTP_USER=DASistemas
      - HTTP_PASSWORD=Ya-Casi-Se-Acaba-El-Semestre!
    ports:
      - 8081:8081
    networks:
      - practica2
    
networks:
  practica2:
    name: practica2